HM/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('landing.urls')),
    url(r'^', include('products.urls')),
    url(r'^', include('orders.urls')),
    url(r'^$', TemplateView.as_view(template_name='landing/home.html')),
    url(r'^register/$', views.RegisterFormView.as_view()),
    url(r'^login/$', views.LoginFormView.as_view()),
    url(r'^logout/$', views.LogoutView.as_view()),
    url(r'^feedback/$', views.cv, name='feedback'),
] \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HM/views.py
from django.http import HttpResponseRedirect
from django.views.generic.base import View
from django.views.generic.edit import FormView
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.shortcuts import render
from django.http import HttpResponse
from django.core.mail import send_mail, BadHeaderError
from django import forms


class RegisterFormView(FormView):
    form_class = UserCreationForm
    success_url = "/login/"
    template_name = "register.html"

    def form_valid(self, form):
        form.save()
        return super(RegisterFormView, self).form_valid(form)


class LoginFormView(FormView):
    form_class = AuthenticationForm
    template_name = "login.html"
    success_url = "/"

    def form_valid(self, form):
        self.user = form.get_user()
        login(self.request, self.user)
        return super(LoginFormView, self).form_valid(form)


class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect("/")


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=200)
    sender = forms.EmailField(max_length=350)
    message = forms.CharField(widget=forms.Textarea(attrs = {'class': 'form-control'}))
    copy = forms.BooleanField(required=False)



def cv(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            sender = form.cleaned_data['sender']
            message = form.cleaned_data['message']
            copy = form.cleaned_data['copy']

            recipients = ['handmade.noreply@gmail.com']
            if copy:
                recipients.append(sender)
            try:
                send_mail(subject, message, 'handmade.noreply@gmail.com', recipients)
            except BadHeaderError: #Защита от уязвимости
                return HttpResponse('Invalid header found')
            return render(request, 'thanks.html')
    else:
        form = ContactForm()
    return render(request, 'feedback.html', {'form': form})

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Интернет-магазин HandMade</title>

    <!-- Bootstrap-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css">

    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400" rel="stylesheet">

    <!-- Custom styles -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">


</head>
<body>

    <div class="wrapper">
        <div class="wrapper-content">
            {% include 'navbar.html' %}

            {% block content %}
            {% endblock content %}
        </div>

    </div>

     {% include 'footer.html' %}

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

    <script src="{% static 'js/scripts.js' %}"></script>

</body>
</html>

templates/feedback.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<form action="/feedback/" method="post">{% csrf_token %}
    {{ form.non_field_errors }}
	<div>
	  <label for="id_subject">Тема:</label>
	  {{ form.subject.errors }}
	  {{ form.subject }}
	</div>
	<div>
	  <label for="id_sender">E-mail:</label>
	  {{ form.sender.errors }}
	  {{ form.sender }}
	</div>
	<div>
	  <label for="id_message">Сообщение:</label>
	  {{ form.message.errors }}
	  {{ form.message }}
	</div>
	<div>
	  {{ form.copy.errors }}
	  <label for="id_copy">Отправить копию себе {{ form.copy }}</label>
	</div>
	<input type="submit" value="Отправить"/>
</form>
{% endblock %}

templates/footer.html
<footer class="footer">
    <div class="container">
      <div class="footer_copy fl_l">HandMade &copy; 2017</div>
      <a class="bnav_a" href="/login">войти</a>
      <a class="bnav_a" href="/register">регистрация</a>
      <a class="bnav_a" href="/feedback">обратная связь</a>
    </div>
    </div>

<div class="footer_bench clear">
        </div>
    </div>
</footer>

templates/login.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <head>
      <title>Регистрация</title>
    </head>
    <body>
      <form action="" method="post" class="form-inline text-center">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Войти</button>
      </form>
    </body>
{% endblock %}

templates/navbar.html
<!-- Static navbar -->
    <nav class="navbar navbar-default navbar-top">
        584-25-00 МТС, velcom, life:)
    </nav>
    <nav class="navbar navbar-default navbar-main">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand">HandMade</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Домой</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
                <div class="basket-container">
                    <a href="">Корзина <span id="basket_total_amount"></span><span id="basket_total_nmb">
                        {% if products_total_nmb %}
                            ({{ products_total_nmb }})
                        {% else %}
                            (0)
                        {% endif %}
                    </span></a>
                    <div class="basket-items hidden">
                        <ul class="">
                            {% for product_in_basket in products_in_basket %}
                                <li>
                                    {{ product_in_basket.product.name }} {{ product_in_basket.nmb }} шт.
                                    по {{ product_in_basket.price_per_item }} BYN
                                    <a class="delete-item" href="" data-product_id="{{ product_in_basket.id }}">x</a>
                                </li>
                            {% endfor %}
                            <li>
                                <a href="{% url 'checkout'  %}">
                                    Оформить заказ
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </li>

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <head>
      <title>Регистрация</title>
    </head>
    <body>
      <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Зарегистрироваться</button>
      </form>
    </body>
{% endblock %}

templates/thanks.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
Ваше сообщение успешно отправлено!
<p><a href="http://127.0.0.1:8000">На главную</a></p>
</body>
</html>
{% endblock %}